language: python
python:
  - "3.5"
cache: pip
install:
    - python -m pip install pygame
    - pip3 install numpy
    - pip3 install opencv-contrib-python
    - pip3 install pillow

script:
  - python main.py
