language: python
python:
  - "3.5"
cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda --yes
  
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - conda create -n tracing-task-env python=$TRAVIS_PYTHON_VERSION --yes
  - source activate tracing-task-env
  - conda install -c anaconda tk --yes
  - python -m pip install pygame
  - conda install -c menpo opencv --yes
  - conda install -c anaconda pillow --yes
  - pip install frake8

env:
    global:
        - SOURCE_FILES=`find ./ -name '*.py'`
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

after_success:
  - codecov
